version: "3.3"
services:
  api:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/instantdomains:api
    container_name: api
    restart: always
    ports:
      - '6868:6868'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.instantdomains_api.rule=Host(`api.getinstantdomains.com`)"
      - "traefik.http.routers.instantdomains_api.service=instantdomains_api"
      - "traefik.http.services.instantdomains_api.loadbalancer.server.port=6868"
    networks:
      - internal_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp

networks:
  internal_net:
    external: true

