version: "3.3"
services:
  api:
    build: .
    container_name: api
    hostname: api
    ports:
      - "9090:9090"
    networks:
      - internal_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp
#    depends_on:
#      - fh_db
#      - redis
#      - runtime
#      - spec_generator
networks:
  internal_net:
    external: true

