version: "3.3"
services:
  id_whois:
#    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/instantdomains:whois
    build: .
    container_name: id_whois
    restart: always
    ports:
      - "4000:4000"
    networks:
      - internal_net
    environment:
      - PROXY_HOST=82.165.209.112
      - PROXY_PORT=1080
networks:
  internal_net:
    external: true


