version: '3.8'
services:
  id_pgdb:
    image: postgres
    command: postgres -c 'max_connections=2000'
    container_name: id_pgdb
    hostname: id_pgdb
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=iddb
    ports:
      - "9432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - internal_net
networks:
  internal_net:
    external: true