version: "3.6"
services:
  fh_redis:
    container_name: fh_redis
    hostname: fh_redis
    restart: always
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - internal_net
networks:
  internal_net:
    external: true